"""initial schema

Revision ID: 079663896a03
Revises: 
Create Date: 2026-10-02 18:30:08.167253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079663896a03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('automated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=60), nullable=False),
    sa.Column('is_saudi', sa.Boolean(), nullable=False),
    sa.Column('gosi_new_system', sa.Boolean(), nullable=False),
    sa.Column('department', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('delegate_id', sa.Integer(), nullable=True),
    sa.Column('delegate_until', sa.Date(), nullable=True),
    sa.Column('basic', sa.Integer(), nullable=False),
    sa.Column('housing', sa.Integer(), nullable=False),
    sa.Column('transport', sa.Integer(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('contract_type', sa.String(length=10), nullable=False),
    sa.Column('contract_no', sa.String(length=40), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('probation_days', sa.Integer(), nullable=False),
    sa.Column('leave_used', sa.Integer(), nullable=False),
    sa.Column('sick_used', sa.Integer(), nullable=False),
    sa.Column('iqama_expiry', sa.Date(), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('bank', sa.String(length=40), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('attendance_id', sa.String(length=20), nullable=True),
    sa.Column('clauses', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('left_date', sa.Date(), nullable=True),
    sa.Column('left_reason', sa.String(length=20), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['delegate_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_code'), ['code'], unique=True)

    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('approved_by', sa.String(length=160), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('total_net', sa.Float(), nullable=True),
    sa.Column('wps_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('wps_uploaded_by', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('tag', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'day')
    )
    with op.batch_alter_table('attendance_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_days_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_days_employee_id'), ['employee_id'], unique=False)

    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_addr', sa.String(length=255), nullable=False),
    sa.Column('to_name', sa.String(length=160), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tag', sa.String(length=40), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=160), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('basic', sa.Float(), nullable=False),
    sa.Column('housing', sa.Float(), nullable=False),
    sa.Column('transport', sa.Float(), nullable=False),
    sa.Column('proration', sa.Float(), nullable=False),
    sa.Column('gosi', sa.Float(), nullable=False),
    sa.Column('loan', sa.Float(), nullable=False),
    sa.Column('absence', sa.Float(), nullable=False),
    sa.Column('additions', sa.Float(), nullable=False),
    sa.Column('deductions', sa.Float(), nullable=False),
    sa.Column('net', sa.Float(), nullable=False),
    sa.Column('bank', sa.String(length=40), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_user_id'), ['user_id'], unique=False)

    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('stage_since', sa.DateTime(), nullable=False),
    sa.Column('reminders_sent', sa.Integer(), nullable=False),
    sa.Column('escalated_to_id', sa.Integer(), nullable=True),
    sa.Column('payroll_month', sa.String(length=7), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['escalated_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requests_employee_id'), ['employee_id'], unique=False)

    op.create_table('support_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.String(length=160), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('due', sa.Date(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('action_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('stage_index', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('addressee', sa.String(length=200), nullable=True),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('issued_by', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('payroll_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('applied_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applied_run_id'], ['payroll_runs.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_adjustments_month'), ['month'], unique=False)

    op.create_table('request_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('effective', sa.Date(), nullable=False),
    sa.Column('field', sa.String(length=30), nullable=False),
    sa.Column('old', sa.String(length=120), nullable=True),
    sa.Column('new', sa.String(length=120), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salary_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_history_employee_id'), ['employee_id'], unique=False)

    op.create_table('scheduled_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('effective', sa.Date(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_changes')
    with op.batch_alter_table('salary_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_history_employee_id'))

    op.drop_table('salary_history')
    op.drop_table('request_events')
    with op.batch_alter_table('payroll_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_adjustments_month'))

    op.drop_table('payroll_adjustments')
    op.drop_table('letters')
    with op.batch_alter_table('action_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_tokens_token_hash'))

    op.drop_table('action_tokens')
    op.drop_table('tasks')
    op.drop_table('support_grants')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_employee_id'))

    op.drop_table('requests')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_user_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('payslips')
    op.drop_table('loans')
    op.drop_table('emails')
    with op.batch_alter_table('attendance_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_days_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_days_day'))

    op.drop_table('attendance_days')
    op.drop_table('assets')
    op.drop_table('settings')
    op.drop_table('payroll_runs')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_code'))

    op.drop_table('employees')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
