"""leave year carry

Revision ID: c13698a779d9
Revises: efabff5245fd
Create Date: 2026-10-04 21:23:01.543929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13698a779d9'
down_revision = 'efabff5245fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column("leave_carry", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('leave_year_start', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('leave_year_start')
        batch_op.drop_column('leave_carry')

    # ### end Alembic commands ###
