"""permissions, request rules, security hardening

بعد الترقية شغّل مرة وحدة: flask --app wsgi encrypt-existing (يشفّر الهوية والآيبان القديمة)

Revision ID: efabff5245fd
Revises: 079663896a03
Create Date: 2026-10-03 06:00:20.722178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efabff5245fd'
down_revision = '079663896a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=120), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_hits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_hits_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_hits_bucket'), ['bucket'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prev_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('hash', sa.String(length=64), nullable=True))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('national_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('iban',
               existing_type=sa.VARCHAR(length=34),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.alter_column('iban',
               existing_type=sa.VARCHAR(length=34),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by_ids', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_last_step', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('perms', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("must_change_password", sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('perms')
        batch_op.drop_column('totp_last_step')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('approved_by_ids')

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.alter_column('iban',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=34),
               existing_nullable=True)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('iban',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=34),
               existing_nullable=True)
        batch_op.alter_column('national_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_column('hash')
        batch_op.drop_column('prev_hash')

    with op.batch_alter_table('rate_hits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_hits_bucket'))
        batch_op.drop_index(batch_op.f('ix_rate_hits_at'))

    op.drop_table('rate_hits')
    # ### end Alembic commands ###
